# Site settings
title: Andriani Papatheodoropoulou
description: Data Analysis Project Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andriani Papatheodoropoulou
user_description: I’m an aspiring data professional with a strong foundation in analytical thinking and problem-solving. Currently pursuing a Master’s in Data Science and Machine Learning and completing a hands-on Data Analytics Bootcamp, I’ve developed skills in Python, SQL, R, and data visualization tools like Power BI.
user_title: Data Analyst
email: andrianipapath@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: andrianipapath
github_username:  apapath
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

