# Site settings
title: Andriani Papatheodoropoulou
description: Data Analysis Project Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andriani Papatheodoropoulou
user_description: I'm a data professional with a strong foundation in analytical thinking, currently working at HarborLab, where I analyze complex operational data and develop algorithmic solutions using JavaScript. Alongside my role, I’m pursuing a Master’s in Data Science and Machine Learning and have completed a hands-on Data Analytics Bootcamp, gaining practical experience in Python, SQL, R, and Power BI. With five years of prior experience in quality control, I bring a detail-oriented, results-driven approach to solving real-world problems. I'm passionate about using data to drive insights, streamline processes, and support smarter decision-making — and I’m now focused on growing my career in data analytics and applied data science.
user_title: Data Analyst
email: andrianipapath@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: andrianipapath
github_username:  apapath
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

